In [32]:
import pandas as pd
from pathlib import Path

# Folder where your files are
folder = Path("../Checking data/")
# Match all files named file1.parquet to file6.parquet
files = sorted(folder.glob("SPO-*.parquet"))

# Read and concatenate them
dfs = [pd.read_parquet(f) for f in files]
df_all = pd.concat(dfs, ignore_index=True)

# Extract station code from Samplingpoint
df_all["station_code"] = df_all["Samplingpoint"].str.extract(r"(RO\d{4}A)")

# Filter only for RO0070A (B-6)
df_b4 = df_all[df_all["station_code"] == "RO0065A"].copy()

print(f"✅ Found {len(df_b4)} rows for station B-4 (RO0065A)")
df_b4.head(-1)

✅ Found 61313 rows for station B-4 (RO0065A)

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog,station_code
0,RO/SPO-RO0065A_00001_100,1,2022-01-01 00:00:00,2022-01-01 01:00:00,4.810000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
1,RO/SPO-RO0065A_00001_100,1,2022-01-01 01:00:00,2022-01-01 02:00:00,4.540000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
2,RO/SPO-RO0065A_00001_100,1,2022-01-01 02:00:00,2022-01-01 03:00:00,4.680000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
3,RO/SPO-RO0065A_00001_100,1,2022-01-01 03:00:00,2022-01-01 04:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
4,RO/SPO-RO0065A_00001_100,1,2022-01-01 04:00:00,2022-01-01 05:00:00,4.620000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61307,RO/SPO-RO0065A_06001_101,6001,2022-12-31 17:00:00,2022-12-31 18:00:00,56.920000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
61308,RO/SPO-RO0065A_06001_101,6001,2022-12-31 18:00:00,2022-12-31 19:00:00,52.060000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
61309,RO/SPO-RO0065A_06001_101,6001,2022-12-31 19:00:00,2022-12-31 20:00:00,49.600000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
61310,RO/SPO-RO0065A_06001_101,6001,2022-12-31 20:00:00,2022-12-31 21:00:00,47.780000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
61311,RO/SPO-RO0065A_06001_101,6001,2022-12-31 21:00:00,2022-12-31 22:00:00,42.640000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A

In [33]:
df_all["Pollutant"].value_counts()

5       52554
8       52554
10      43795
1       35036
20      26277
7       17518
6001     8759
Name: Pollutant, dtype: int64

In [34]:
df_all.groupby("Pollutant").head(3)

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog,station_code
0,RO/SPO-RO0065A_00001_100,1,2022-01-01 00:00:00,2022-01-01 01:00:00,4.810000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
1,RO/SPO-RO0065A_00001_100,1,2022-01-01 01:00:00,2022-01-01 02:00:00,4.540000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
2,RO/SPO-RO0065A_00001_100,1,2022-01-01 02:00:00,2022-01-01 03:00:00,4.680000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3,RO0065A
8759,RO/SPO-RO0065A_00005_101,5,2022-01-01 00:00:00,2022-01-01 01:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,9257d02c-fa75-4767-bed6-ee7d1f4a2f3a,RO0065A
8760,RO/SPO-RO0065A_00005_101,5,2022-01-01 01:00:00,2022-01-01 02:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,9257d02c-fa75-4767-bed6-ee7d1f4a2f3a,RO0065A
8761,RO/SPO-RO0065A_00005_101,5,2022-01-01 02:00:00,2022-01-01 03:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,9257d02c-fa75-4767-bed6-ee7d1f4a2f3a,RO0065A
17518,RO/SPO-RO0065A_00007_100,7,2022-01-01 00:00:00,2022-01-01 01:00:00,11.070000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,b4160ed8-822b-44e0-b0d7-1ac3c6bf21f6,RO0065A
17519,RO/SPO-RO0065A_00007_100,7,2022-01-01 01:00:00,2022-01-01 02:00:00,11.580000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,b4160ed8-822b-44e0-b0d7-1ac3c6bf21f6,RO0065A
17520,RO/SPO-RO0065A_00007_100,7,2022-01-01 02:00:00,2022-01-01 03:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,b4160ed8-822b-44e0-b0d7-1ac3c6bf21f6,RO0065A
26277,RO/SPO-RO0065A_00008_100,8,2022-01-01 00:00:00,2022-01-01 01:00:00,17.870000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,e719fc6b-a4b3-48dd-9d73-3104e6eb29ec,RO0065A
26278,RO/SPO-RO0065A_00008_100,8,2022-01-01 01:00:00,2022-01-01 02:00:00,18.270000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,e719fc6b-a4b3-48dd-9d73-3104e6eb29ec,RO0065A
26279,RO/SPO-RO0065A_00008_100,8,2022-01-01 02:00:00,2022-01-01 03:00:00,13.840000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,e719fc6b-a4b3-48dd-9d73-3104e6eb29ec,RO0065A
35036,RO/SPO-RO0065A_00010_100,10,2022-01-01 00:00:00,2022-01-01 01:00:00,0.680000000000000000,mg.m-3,hour,1,1,2023-09-26 14:37:36,None,3905c4b9-e62f-44fa-a0c4-e688c27892a4,RO0065A
35037,RO/SPO-RO0065A_00010_100,10,2022-01-01 01:00:00,2022-01-01 02:00:00,0.670000000000000000,mg.m-3,hour,1,1,2023-09-26 14:37:36,None,3905c4b9-e62f-44fa-a0c4-e688c27892a4,RO0065A
35038,RO/SPO-RO0065A_00010_100,10,2022-01-01 02:00:00,2022-01-01 03:00:00,0.700000000000000000,mg.m-3,hour,1,1,2023-09-26 14:37:36,None,3905c4b9-e62f-44fa-a0c4-e688c27892a4,RO0065A
43795,RO/SPO-RO0065A_00020_100,20,2022-01-01 00:00:00,2022-01-01 01:00:00,1.480000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3654905b-33ca-452d-8a6e-0c6c4ead22fa,RO0065A
43796,RO/SPO-RO0065A_00020_100,20,2022-01-01 01:00:00,2022-01-01 02:00:00,1.420000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3654905b-33ca-452d-8a6e-0c6c4ead22fa,RO0065A
43797,RO/SPO-RO0065A_00020_100,20,2022-01-01 02:00:00,2022-01-01 03:00:00,1.250000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3654905b-33ca-452d-8a6e-0c6c4ead22fa,RO0065A
52554,RO/SPO-RO0065A_06001_101,6001,2022-01-01 00:00:00,2022-01-01 01:00:00,97.230000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
52555,RO/SPO-RO0065A_06001_101,6001,2022-01-01 01:00:00,2022-01-01 02:00:00,58.210000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A
52556,RO/SPO-RO0065A_06001_101,6001,2022-01-01 02:00:00,2022-01-01 03:00:00,41.240000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,3443a30d-a26d-4740-ad8a-1212ddbf7a7e,RO0065A

In [35]:
pollutant_map = {
    1: "PM10",
    6001: "PM2.5",
    7: "NO2",
}

df_all["PollutantName"] = df_all["Pollutant"].map(pollutant_map)

In [36]:
df_all[["Pollutant", "PollutantName"]].drop_duplicates()

       Pollutant PollutantName
0              1          PM10
8759           5           NaN
17518          7           NO2
26277          8           NaN
35036         10           NaN
43795         20           NaN
52554       6001         PM2.5

In [24]:
import pandas as pd
from pathlib import Path

file = Path("../Checking data/").glob("SPO-RO0065A_00001_100.parquet")
first_file = next(file)

df_sample = pd.read_parquet(first_file)
print(df_sample.columns)
df_sample.head(10)

Index(['Samplingpoint', 'Pollutant', 'Start', 'End', 'Value', 'Unit',
       'AggType', 'Validity', 'Verification', 'ResultTime', 'DataCapture',
       'FkObservationLog'],
      dtype='object')

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog
0,RO/SPO-RO0065A_00001_100,1,2022-01-01 00:00:00,2022-01-01 01:00:00,4.810000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
1,RO/SPO-RO0065A_00001_100,1,2022-01-01 01:00:00,2022-01-01 02:00:00,4.540000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
2,RO/SPO-RO0065A_00001_100,1,2022-01-01 02:00:00,2022-01-01 03:00:00,4.680000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
3,RO/SPO-RO0065A_00001_100,1,2022-01-01 03:00:00,2022-01-01 04:00:00,0E-18,ug.m-3,hour,-1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
4,RO/SPO-RO0065A_00001_100,1,2022-01-01 04:00:00,2022-01-01 05:00:00,4.620000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
5,RO/SPO-RO0065A_00001_100,1,2022-01-01 05:00:00,2022-01-01 06:00:00,4.450000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
6,RO/SPO-RO0065A_00001_100,1,2022-01-01 06:00:00,2022-01-01 07:00:00,3.920000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
7,RO/SPO-RO0065A_00001_100,1,2022-01-01 07:00:00,2022-01-01 08:00:00,3.800000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
8,RO/SPO-RO0065A_00001_100,1,2022-01-01 08:00:00,2022-01-01 09:00:00,3.990000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3
9,RO/SPO-RO0065A_00001_100,1,2022-01-01 09:00:00,2022-01-01 10:00:00,4.780000000000000000,ug.m-3,hour,1,1,2023-09-26 14:37:36,None,a1374adf-eff7-4282-b6fa-1fa48250a8d3

In [1]:
import pandas as pd
from pathlib import Path

# Folder where your files are
folder = Path("../Checking data/pm10_2013-2023")
# Match all files named file1.parquet to file6.parquet
files = sorted(folder.glob("SPO-*.parquet"))

# Read and concatenate them
dfs = [pd.read_parquet(f) for f in files]
df_all = pd.concat(dfs, ignore_index=True)

# Extract station code from Samplingpoint
df_all["station_code"] = df_all["Samplingpoint"].str.extract(r"(RO\d{4}A)")

# Filter only for RO0070A (B-6)
df_b4 = df_all[df_all["station_code"] == "RO0229A"].copy()

print(f"✅ Found {len(df_b4)} rows for station B-4 (RO0065A)")
df_b4.head(-1)

✅ Found 0 rows for station B-4 (RO0065A)

Empty DataFrame
Columns: [Samplingpoint, Pollutant, Start, End, Value, Unit, AggType, Validity, Verification, ResultTime, DataCapture, FkObservationLog, station_code]
Index: []

In [53]:
import pandas as pd
from pathlib import Path

# Folder where your files are
folder = Path("../Checking data/no2_2013-2023")

# Match all files named file1.parquet to file6.parquet
files = sorted(folder.glob("SPO-*.parquet"))

# Read and concatenate them
dfs = [pd.read_parquet(f) for f in files]
df_all = pd.concat(dfs, ignore_index=True)

# Extract station code from Samplingpoint
df_all["station_code"] = df_all["Samplingpoint"].str.extract(r"(RO\d{4}A)")

# Filter only for RO0070A (B-6)
df_b4 = df_all[df_all["station_code"] == "RO0229A"].copy()

print(f"✅ Found {len(df_b4)} rows for station B-4 (RO0065A)")
df_b4.head(-1)

✅ Found 8760 rows for station B-4 (RO0065A)

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog,station_code
376912,RO/SPO-RO0229A_00008_100,8,2022-12-31 23:00:00,2023-01-01 00:00:00,33.670000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
376913,RO/SPO-RO0229A_00008_100,8,2023-01-01 00:00:00,2023-01-01 01:00:00,20.960000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
376914,RO/SPO-RO0229A_00008_100,8,2023-01-01 01:00:00,2023-01-01 02:00:00,23.700000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
376915,RO/SPO-RO0229A_00008_100,8,2023-01-01 02:00:00,2023-01-01 03:00:00,26.200000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
376916,RO/SPO-RO0229A_00008_100,8,2023-01-01 03:00:00,2023-01-01 04:00:00,0E-18,ug.m-3,hour,-1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
385666,RO/SPO-RO0229A_00008_100,8,2023-12-31 17:00:00,2023-12-31 18:00:00,98.170000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
385667,RO/SPO-RO0229A_00008_100,8,2023-12-31 18:00:00,2023-12-31 19:00:00,91.760000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
385668,RO/SPO-RO0229A_00008_100,8,2023-12-31 19:00:00,2023-12-31 20:00:00,84.680000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
385669,RO/SPO-RO0229A_00008_100,8,2023-12-31 20:00:00,2023-12-31 21:00:00,70.280000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A
385670,RO/SPO-RO0229A_00008_100,8,2023-12-31 21:00:00,2023-12-31 22:00:00,58.230000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,326585ee-29da-4b8f-89ef-1a1185608486,RO0229A

In [50]:
import pandas as pd
from pathlib import Path

# Folder where your files are
folder = Path("../Checking data/pm25_2013-2023")

# Match all files named file1.parquet to file6.parquet
files = sorted(folder.glob("SPO-*.parquet"))

# Read and concatenate them
dfs = [pd.read_parquet(f) for f in files]
df_all = pd.concat(dfs, ignore_index=True)

# Extract station code from Samplingpoint
df_all["station_code"] = df_all["Samplingpoint"].str.extract(r"(RO\d{4}A)")

# Filter only for RO0070A (B-6)
df_b4 = df_all[df_all["station_code"] == "RO0229A"].copy()

print(f"✅ Found {len(df_b4)} rows for station B-4 (RO0065A)")
df_b4.head(-1)

✅ Found 8760 rows for station B-4 (RO0065A)

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog,station_code
17520,RO/SPO-RO0229A_06001_101,6001,2022-12-31 23:00:00,2023-01-01 00:00:00,213.030000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
17521,RO/SPO-RO0229A_06001_101,6001,2023-01-01 00:00:00,2023-01-01 01:00:00,80.270000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
17522,RO/SPO-RO0229A_06001_101,6001,2023-01-01 01:00:00,2023-01-01 02:00:00,73.470000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
17523,RO/SPO-RO0229A_06001_101,6001,2023-01-01 02:00:00,2023-01-01 03:00:00,69.890000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
17524,RO/SPO-RO0229A_06001_101,6001,2023-01-01 03:00:00,2023-01-01 04:00:00,60.730000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26274,RO/SPO-RO0229A_06001_101,6001,2023-12-31 17:00:00,2023-12-31 18:00:00,111.590000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
26275,RO/SPO-RO0229A_06001_101,6001,2023-12-31 18:00:00,2023-12-31 19:00:00,144.870000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
26276,RO/SPO-RO0229A_06001_101,6001,2023-12-31 19:00:00,2023-12-31 20:00:00,138.060000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
26277,RO/SPO-RO0229A_06001_101,6001,2023-12-31 20:00:00,2023-12-31 21:00:00,94.660000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A
26278,RO/SPO-RO0229A_06001_101,6001,2023-12-31 21:00:00,2023-12-31 22:00:00,85.920000000000000000,ug.m-3,hour,1,1,2024-09-16 11:38:52,None,b13e3a52-488e-44cb-af44-5d5a1cb63021,RO0229A

In [2]:
import requests
import pandas as pd
from tqdm import tqdm

# Parametrii generali
CITY = "Bucharest"
PARAMETERS = ["pm10", "pm25", "no2"]
DATE_FROM = "2023-01-01"
DATE_TO = "2023-12-31"
LIMIT = 10000  # API-ul permite până la 10.000 pe request

def fetch_openaq_data(parameter):
    print(f"🔄 Fetching {parameter.upper()} data for {CITY} in 2023...")
    url = "https://api.openaq.org/v2/measurements"
    page = 1
    all_results = []

    while True:
        params = {
            "city": CITY,
            "parameter": parameter,
            "date_from": DATE_FROM,
            "date_to": DATE_TO,
            "limit": LIMIT,
            "page": page,
            "sort": "asc",
            "order_by": "datetime"
        }

        response = requests.get(url, params=params)
        data = response.json()

        if "results" not in data or len(data["results"]) == 0:
            break

        all_results.extend(data["results"])
        print(f"📦 Page {page} - Retrieved {len(data['results'])} rows")

        if len(data["results"]) < LIMIT:
            break

        page += 1

    return pd.DataFrame(all_results)

# Descărcăm datele pentru fiecare poluant
dfs = {}
for param in PARAMETERS:
    df = fetch_openaq_data(param)
    if not df.empty:
        df["pollutant"] = param.upper()
        dfs[param] = df

# Combinăm totul într-un singur DataFrame
df_all = pd.concat(dfs.values(), ignore_index=True)

# Păstrăm coloanele utile
df_clean = df_all[["location", "parameter", "value", "unit", "date"]].copy()
df_clean["datetime"] = pd.to_datetime(df_clean["date"].apply(lambda d: d["utc"]))
df_clean.drop(columns=["date"], inplace=True)

print("✅ Date extrase:")
print(df_clean.head())

# Salvează opțional în CSV
df_clean.to_csv("bucharest_air_quality_2023.csv", index=False)

🔄 Fetching PM10 data for Bucharest in 2023...
🔄 Fetching PM25 data for Bucharest in 2023...
🔄 Fetching NO2 data for Bucharest in 2023...

ValueError: No objects to concatenate